scorbot:

  # Arm Trajectory Controllers ---------------------------------------
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - scorbot_joint_1
      - scorbot_joint_2
      - scorbot_joint_3
      - scorbot_joint_4
      - scorbot_joint_5

  # Gripper Trajectory Controllers ---------------------------------------
  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - scorbot_pad1_joint