controller_list:
  - name: fake_scorbot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - scorbot_joint_1
      - scorbot_joint_2
      - scorbot_joint_3
      - scorbot_joint_4
      - scorbot_joint_5
  - name: fake_scorbot_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - scorbot_pad1_joint
initial:  # Define initial robot poses.
  - group: scorbot_arm
    pose: start_pos