# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: scorbot_arm
  joint_model_group_pose: start_pos
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - scorbot_joint_1
    - scorbot_joint_2
    - scorbot_joint_3
    - scorbot_joint_4
    - scorbot_joint_5
    - scorbot_pad1_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - scorbot_joint_1
    - scorbot_joint_2
    - scorbot_joint_3
    - scorbot_joint_4
    - scorbot_joint_5
  gains:
    scorbot_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    scorbot_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    scorbot_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    scorbot_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    scorbot_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    scorbot_pad1_joint
  gains:
    scorbot_pad1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1


controller_list:
  - name: scorbot/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - scorbot_joint_1
      - scorbot_joint_2
      - scorbot_joint_3
      - scorbot_joint_4
      - scorbot_joint_5
  - name: scorbot/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - scorbot_pad1_joint